### ISSUE TITLE
安装过程报错，貌似python3的问题

### ISSUE THREAD

**Issue by sunpma** [8838/btpanel-v7.7.0#7]
甲骨文ARM Ubuntu 20.04/Ubuntu 22.04 均报错
错误代码：
```
ERROR: Exception:
Traceback (most recent call last):
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/www/server/panel/pyenv/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/www/server/panel/pyenv/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/www/server/panel/pyenv/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/www/server/panel/pyenv/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 378, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 96, in resolve
    collected.requirements, max_rounds=limit_how_complex_resolution_can_be
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 183, in _make_candidate_from_link
    link, template, name, version
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 233, in _make_base_candidate_from_link
    version=version,
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 296, in __init__
    version=version,
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 602, in _prepare_linked_requirement
    hashes,
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 172, in unpack_url
    hashes=hashes,
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 109, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 87, in response_chunks
    decode_content=False,
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/www/server/panel/pyenv/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mirrors.aliyun.com', port=443): Read timed out.
```

**Comment by 8838** [comment]
先将系统dd为debian10
